version: 2
jobs:
  build:
    steps:
      - checkout:
      - run:
          name: Install Packages
          command: yarn install
      # - run:
      #     name: Run Tests
      #     command: |
      #       . venv/bin/activate
      #       python manage.py test
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results
      #     destination: tr1

  deploy:
    steps:
      - checkout:
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Deploy
          command: sls deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - hold
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - /master/